### ISSUE TITLE
Network Error: Failed to Fetch [CORS ERROR]

### ISSUE THREAD

**Issue by amitosh1995** [mirumee/saleor-storefront#206] opened 2019-01-16 17:04 UTC
### What I'm trying to achieve

I downloaded the saleor 2.2.0 release and its running properly on "http://localhost:8000/" with the old UI. 
For the new UI, i downloaded the saleor-storefront. and completed all the steps including npm i and npm start
but when i run the new UI port "http://localhost:3000/" . Some portion of the UI is available but some Part shows "NETWORK ERROR : FAILED TO FETCH" 

so i tried to debug the app from chrome console.. and it shows that the problem is associated with CORS and Access-Control-Allow-Origin' header contains multiple values .

### Steps to reproduce the problem
1. 
2. 

### What I expected to happen
…  Can someone please explain why is this happening and how can i resolve this error ?

### Screenshots

**System information**
Operating system: Windows 10 Professional 64 bit
Browser: Google Chrome

**Comment by amitosh1995** [comment] 2019-01-16 17:12
I am uploading a screenshot of how the New UI page looks
![untitled](https://user-images.githubusercontent.com/29412198/51265925-e44a8080-19df-11e9-89aa-0012aa1a752d.png)

**Comment by maarcingebala** [comment] 2019-01-17 09:14
@amitosh1995 Did you set `BACKEND_URL` env variable in the terminal that you're running the storefront app? You should set `BACKEND_URL` to `http://localhost:8000/`.

**Comment by amitosh1995** [comment] 2019-01-17 11:05
The problem does not arrive when i clone the original repository of mirumee. It setups smooth, but when i fork the repository, and try to work on my repository then the problem appears.

@maarcingebala yes i have listed the `http://localhost:8000/` in the index.tsx file. Is there any other way i should set this?

**Comment by amitosh1995** [comment] 2019-01-17 12:09
@piotrgrundas i did as you said. now CORS problem is resolved but its showing BAD REQUEST.
![untitled1](https://user-images.githubusercontent.com/29412198/51317832-a6506980-1a7e-11e9-8875-b8d805281214.png)

**Comment by piotrgrundas** [comment] 2019-01-17 12:42
@amitosh1995 U need to add backend env var to storefront also. Personally I use virtualenvwrapper post hooks for it:

```
cat ~/.virtualenvs/saleor-fron/bin/postactivate
#!/bin/zsh
# This hook is sourced after this virtualenv is activated.

export BACKEND_URL='http://127.0.0.1:8000/'
nvm use 10.9.0
```

**Comment by amitosh1995** [comment] 2019-01-17 15:52
@piotrgrundas and @maarcingebala Thank you. I can see the UI after setting the env var

But dashboard is not working and i cannot see the dashboard or user profile in the new UI. i have uploaded the screenshot
![untitled2](https://user-images.githubusercontent.com/29412198/51330699-01de1f80-1a9e-11e9-9c4d-3b0223306b17.png)

**Comment by piotrgrundas** [comment] 2019-01-17 16:40
Well, that's probably because locally dashboard is served from the backend and it's running on a different port. 
Try `http://127.0.0.1:8000/dashboard/`

Closing this ticket since the issue is resolved.

**Closed** 2019-01-17 16:40 UTC

**Comment by ntekka** [comment] 2020-02-01 00:43
I think I found the reason for this elusive bug, the initial OPTIONS request is for /graphql (NO TRAILING SLASH), and that doesn't match the URL pattern and gets redirected to /graphql/ with an HTTP status 302.
My quick fix for this is to make ending slash optional in the urlpatterns array in saleor/urls.py line 14:
```
    url(r"^graphql/?", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
```
```
urlpatterns = [
    url(r"^graphql/?", csrf_exempt(GraphQLView.as_view(schema=schema)), name="api"),
    url(r"^feeds/", include((feed_urls, "data_feeds"), namespace="data_feeds")),
    url(
        r"^digital-download/(?P<token>[0-9A-Za-z_\-]+)/$",
        digital_product,
        name="digital-product",
    ),
]```

**Comment by ramirovazq** [comment] 2020-03-17 13:00
I had put in backend  `ALLOWED_HOSTS = ["*"]` but still was not working.  The situation, was like ntekka mention, i was running the command  `$ API_URI=http://127.0.0.1:8000/graphql npm start` without slash at the end of graphql, so the correct way is `$ API_URI=http://127.0.0.1:8000/graphql/ npm start`

**Comment by aquaerius** [comment] 2020-04-26 12:44
The ALLOWED_HOSTS don´t need to be any, I have ALLOWED_HOSTS="127.0.01,localhost" and it runs as intended. I was missing the slash at the end of graphql `API_URI=http://localhost:8000/graphql/ npm start`

**Comment by lecongphuc92** [comment] 2020-06-05 12:08
I'm getting the same error even though I've tried all of the above :(

**Comment by haydenfoote** [comment] 2020-06-27 06:50
Hi Phuc, did you eventually work out the error?

**Comment by Batgerel53** [comment] 2021-12-13 02:02
@amitosh1995 , @haydenfoote , @ramirovazq   HI guys,  id you eventually work out the error?
