### ISSUE TITLE
Took too long to load the BAG

### ISSUE THREAD

**Issue by Sanaj2060** [mirumee/saleor-storefront#733] opened 2020-05-23 11:52 UTC
I clone the Saleor-core, Saleor-storefront and Saleor-dashboard and run locally. Everything is working fine. But when I add items to the bag and click the **_bag_** icon at the storefront, it gives the following error:

> ERROR saleor.graphql.errors.handled A query
had an error [PID:11932:Thread-65]
graphql.error.base.GraphQLError: Fields "quantityAvailable" conflict because they have differing arguments. Use different aliases on the fields to fetch both if this was intentional.

**Comment by gusreyes01** [comment] 2020-05-23 19:17
Got the same error when cloning and running a brand new build of the saleor-platform repo.

**Comment by giovannipiccinelli** [comment] 2020-05-24 09:41
This is same as #732 I have the same issue

**Comment by maarcingebala** [comment] 2020-05-25 10:01
Closing as this is duplicate of #732

**Closed by maarcingebala** 2020-05-25 10:01 UTC
