### ISSUE TITLE
Product with no shopping method can't be checked out nor removed from cart

### ISSUE THREAD

**Issue by samuelOsborne** [mirumee/saleor-storefront#628] opened 2020-02-26 13:07 UTC
### What I'm trying to achieve
Order and purchase a digital product.

### Steps to reproduce the problem
1. Create a product type that doesn't require shipping
2. Create product with product type created in previous step
3. Add product to cart
4. Add billing method and proceed to checkout
5. /checkout/review fails with message: `checkout.shippingMethod is null`
6. Go back to homepage, deleting the product from dropdown cart doesn't work
7. Deleting product from cart in the shopping bag page doesn't work, popup error message:
```
Error
Could not add item Loading widget (111). Only 0 remaining in stock.
```

However there are plenty in stock

### What I expected to happen
Be able to purchase a digital product

**System information**
Operating system: Elementary OS
Browser: Firefox
Created using the saleor-platform repo

**Comment by karolkielecki** [comment] 2020-03-03 09:44
@samuelOsborne Hi there! Thank you for reporting. We'll investigate it as soon as we can. It looks like a bug...

**Comment by dsbrgg** [comment] 2020-03-11 10:47
Fell into the same issue. [I suppose the cart should just ignore the delivery cost in this situation](https://github.com/mirumee/saleor-storefront/blob/master/src/checkout/views/Review/View.tsx#L87).

**Comment by boreBoar** [comment] 2020-03-24 06:24
Did anyone find a working solution for this?

**Comment by maarcingebala** [comment] 2020-03-24 10:05
Hey, we're looking into this, should be fixed this week.

**Closed** 2020-03-24 10:41 UTC
Labels: bug

**Comment by maarcingebala** [comment] 2020-03-24 10:42
@samuelOsborne @dsbrgg @boreBoar Can you please update to the newest `master` and see if the issue is resolved now for you?
